---
title: "Right Wing Populism, Ethical Issues"
author: "Fianko Buckle & Travis James Smith"
date: "May 11, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In exploring whether or not a correlation exists between left-right ideology and pluralism in our dataset, our analysis found that many socially conservative parties skewed very populist, while more socially left-wing parties tended to have more centralized values with regards to populism. Ultimately we found that when looking at the correlation between ideology and populism, there were peaks for people who were "central-left, central pluralist" and "hard-right, hard populist".

There are a few ethical pitfalls pertaining to extreme populism, regardless of whether or not a party is socially left or right. Extreme right-wing populism tends to be very anti-elitist, and hence against many international organizations (such as the European Union for example). This form of populism can be especially dangerous in times of economic crisis when anger and sentiments are high, giving rise to a variety of social issues and systematic oppression (xenophobia, racism, etc.). A political party that adopts heavy populist rhetoric poses the risk of creating more dichotomous stances on political issues. Views that oppose a hard populist political party are often labeled as "elitist", which in turn causes more polarization in a region's political culture.

Two examples of countries fully controlled by populist political parties are Hungary and Venezuela. In these countries, populist leaders have brought in new constitutions and have restructured their governments such that the checks and balances within the previous, more liberally democratic governments have been undermined. As a result, the power of branches in these governments remains unchecked by other branches and political parties with differing views, breeding a political environment even more conducive to polarization.
